// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sldb

import (
	"context"
	"database/sql"
	"time"
)

const countActiveAuthInvitesByCreatorAndRole = `-- name: CountActiveAuthInvitesByCreatorAndRole :one
SELECT COUNT(1)
FROM auth_invite
WHERE created_by = ?
  AND role = ?
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > ?
`

type CountActiveAuthInvitesByCreatorAndRoleParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	Role      string        `db:"role" json:"role"`
	ExpiresAt time.Time     `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CountActiveAuthInvitesByCreatorAndRole(ctx context.Context, arg CountActiveAuthInvitesByCreatorAndRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAuthInvitesByCreatorAndRole, arg.CreatedBy, arg.Role, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthUsers = `-- name: CountAuthUsers :one
SELECT COUNT(1) FROM auth_user
`

func (q *Queries) CountAuthUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthApiKey = `-- name: CreateAuthApiKey :exec
INSERT INTO auth_api_key (id, user_id, key_hash, label, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuthApiKeyParams struct {
	ID        string       `db:"id" json:"id"`
	UserID    int64        `db:"user_id" json:"user_id"`
	KeyHash   string       `db:"key_hash" json:"key_hash"`
	Label     string       `db:"label" json:"label"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAuthApiKey(ctx context.Context, arg CreateAuthApiKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAuthApiKey,
		arg.ID,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
		arg.ExpiresAt,
	)
	return err
}

const createAuthInvite = `-- name: CreateAuthInvite :exec
INSERT INTO auth_invite (id, code_hash, role, expires_at, created_by)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuthInviteParams struct {
	ID        string        `db:"id" json:"id"`
	CodeHash  string        `db:"code_hash" json:"code_hash"`
	Role      string        `db:"role" json:"role"`
	ExpiresAt time.Time     `db:"expires_at" json:"expires_at"`
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAuthInvite(ctx context.Context, arg CreateAuthInviteParams) error {
	_, err := q.db.ExecContext(ctx, createAuthInvite,
		arg.ID,
		arg.CodeHash,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_session (
    id, user_id, session_token_hash, remember_token_hash,
    expires_at, remember_expires_at, user_agent, client_ip
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuthSessionParams struct {
	ID                string    `db:"id" json:"id"`
	UserID            int64     `db:"user_id" json:"user_id"`
	SessionTokenHash  string    `db:"session_token_hash" json:"session_token_hash"`
	RememberTokenHash string    `db:"remember_token_hash" json:"remember_token_hash"`
	ExpiresAt         time.Time `db:"expires_at" json:"expires_at"`
	RememberExpiresAt time.Time `db:"remember_expires_at" json:"remember_expires_at"`
	UserAgent         string    `db:"user_agent" json:"user_agent"`
	ClientIp          string    `db:"client_ip" json:"client_ip"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.SessionTokenHash,
		arg.RememberTokenHash,
		arg.ExpiresAt,
		arg.RememberExpiresAt,
		arg.UserAgent,
		arg.ClientIp,
	)
	return err
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_user (username, password_hash, role, status)
VALUES (?, ?, ?, ?)
RETURNING id, created_at, updated_at
`

type CreateAuthUserParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
	Status       string `db:"status" json:"status"`
}

type CreateAuthUserRow struct {
	ID        int64     `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (CreateAuthUserRow, error) {
	row := q.db.QueryRowContext(ctx, createAuthUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i CreateAuthUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteAuthApiKey = `-- name: DeleteAuthApiKey :execrows
DELETE FROM auth_api_key
WHERE id = ? AND user_id = ?
`

type DeleteAuthApiKeyParams struct {
	ID     string `db:"id" json:"id"`
	UserID int64  `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteAuthApiKey(ctx context.Context, arg DeleteAuthApiKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuthApiKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAuthUserByID = `-- name: DeleteAuthUserByID :execrows
DELETE FROM auth_user
WHERE id = ?
`

func (q *Queries) DeleteAuthUserByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuthUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM auth_session
WHERE remember_expires_at <= ? OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, rememberExpiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthSessions, rememberExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthApiKeyByKeyHash = `-- name: GetAuthApiKeyByKeyHash :one
SELECT id, user_id, key_hash, label, created_at, expires_at, last_used_at
FROM auth_api_key
WHERE key_hash = ?
`

func (q *Queries) GetAuthApiKeyByKeyHash(ctx context.Context, keyHash string) (AuthApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAuthApiKeyByKeyHash, keyHash)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAuthInviteByCodeHash = `-- name: GetAuthInviteByCodeHash :one
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE code_hash = ?
`

func (q *Queries) GetAuthInviteByCodeHash(ctx context.Context, codeHash string) (AuthInvite, error) {
	row := q.db.QueryRowContext(ctx, getAuthInviteByCodeHash, codeHash)
	var i AuthInvite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Role,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthSessionByRememberTokenHash = `-- name: GetAuthSessionByRememberTokenHash :one
SELECT id, user_id, session_token_hash, remember_token_hash,
       expires_at, remember_expires_at, revoked_at,
       user_agent, client_ip, created_at, updated_at
FROM auth_session
WHERE remember_token_hash = ?
`

func (q *Queries) GetAuthSessionByRememberTokenHash(ctx context.Context, rememberTokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getAuthSessionByRememberTokenHash, rememberTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.RememberTokenHash,
		&i.ExpiresAt,
		&i.RememberExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.ClientIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionBySessionTokenHash = `-- name: GetAuthSessionBySessionTokenHash :one
SELECT id, user_id, session_token_hash, remember_token_hash,
       expires_at, remember_expires_at, revoked_at,
       user_agent, client_ip, created_at, updated_at
FROM auth_session
WHERE session_token_hash = ?
`

func (q *Queries) GetAuthSessionBySessionTokenHash(ctx context.Context, sessionTokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getAuthSessionBySessionTokenHash, sessionTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.RememberTokenHash,
		&i.ExpiresAt,
		&i.RememberExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.ClientIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM auth_user
WHERE id = ?
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id int64) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByUsername = `-- name: GetAuthUserByUsername :one
SELECT id, username, password_hash, role, status, created_at, updated_at
FROM auth_user
WHERE username = ?
`

func (q *Queries) GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAuthInvitesByCreator = `-- name: ListActiveAuthInvitesByCreator :many
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE created_by = ?
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListActiveAuthInvitesByCreatorParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	ExpiresAt time.Time     `db:"expires_at" json:"expires_at"`
	Limit     int64         `db:"limit" json:"limit"`
	Offset    int64         `db:"offset" json:"offset"`
}

func (q *Queries) ListActiveAuthInvitesByCreator(ctx context.Context, arg ListActiveAuthInvitesByCreatorParams) ([]AuthInvite, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAuthInvitesByCreator,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthInvite
	for rows.Next() {
		var i AuthInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthApiKeysByUserID = `-- name: ListAuthApiKeysByUserID :many
SELECT id, user_id, key_hash, label, created_at, expires_at, last_used_at
FROM auth_api_key
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAuthApiKeysByUserID(ctx context.Context, userID int64) ([]AuthApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAuthApiKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthApiKey
	for rows.Next() {
		var i AuthApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.Label,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthInvitesByCreator = `-- name: ListAuthInvitesByCreator :many
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE created_by = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuthInvitesByCreatorParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	Limit     int64         `db:"limit" json:"limit"`
	Offset    int64         `db:"offset" json:"offset"`
}

func (q *Queries) ListAuthInvitesByCreator(ctx context.Context, arg ListAuthInvitesByCreatorParams) ([]AuthInvite, error) {
	rows, err := q.db.QueryContext(ctx, listAuthInvitesByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthInvite
	for rows.Next() {
		var i AuthInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAuthInvitesByCreator = `-- name: ListExpiredAuthInvitesByCreator :many
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE created_by = ?
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND expires_at <= ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListExpiredAuthInvitesByCreatorParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	ExpiresAt time.Time     `db:"expires_at" json:"expires_at"`
	Limit     int64         `db:"limit" json:"limit"`
	Offset    int64         `db:"offset" json:"offset"`
}

func (q *Queries) ListExpiredAuthInvitesByCreator(ctx context.Context, arg ListExpiredAuthInvitesByCreatorParams) ([]AuthInvite, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredAuthInvitesByCreator,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthInvite
	for rows.Next() {
		var i AuthInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedAuthInvitesByCreator = `-- name: ListRevokedAuthInvitesByCreator :many
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE created_by = ?
  AND revoked_at IS NOT NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListRevokedAuthInvitesByCreatorParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	Limit     int64         `db:"limit" json:"limit"`
	Offset    int64         `db:"offset" json:"offset"`
}

func (q *Queries) ListRevokedAuthInvitesByCreator(ctx context.Context, arg ListRevokedAuthInvitesByCreatorParams) ([]AuthInvite, error) {
	rows, err := q.db.QueryContext(ctx, listRevokedAuthInvitesByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthInvite
	for rows.Next() {
		var i AuthInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedAuthInvitesByCreator = `-- name: ListUsedAuthInvitesByCreator :many
SELECT id, code_hash, role, expires_at, used_at, used_by, created_by, revoked_at, created_at
FROM auth_invite
WHERE created_by = ?
  AND used_at IS NOT NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsedAuthInvitesByCreatorParams struct {
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	Limit     int64         `db:"limit" json:"limit"`
	Offset    int64         `db:"offset" json:"offset"`
}

func (q *Queries) ListUsedAuthInvitesByCreator(ctx context.Context, arg ListUsedAuthInvitesByCreatorParams) ([]AuthInvite, error) {
	rows, err := q.db.QueryContext(ctx, listUsedAuthInvitesByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthInvite
	for rows.Next() {
		var i AuthInvite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Role,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthInviteUsed = `-- name: MarkAuthInviteUsed :execrows
UPDATE auth_invite
SET used_at = ?, used_by = ?
WHERE id = ? AND used_at IS NULL AND revoked_at IS NULL
`

type MarkAuthInviteUsedParams struct {
	UsedAt sql.NullTime  `db:"used_at" json:"used_at"`
	UsedBy sql.NullInt64 `db:"used_by" json:"used_by"`
	ID     string        `db:"id" json:"id"`
}

func (q *Queries) MarkAuthInviteUsed(ctx context.Context, arg MarkAuthInviteUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAuthInviteUsed, arg.UsedAt, arg.UsedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAuthInvite = `-- name: RevokeAuthInvite :execrows
UPDATE auth_invite
SET revoked_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeAuthInviteParams struct {
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
	ID        string       `db:"id" json:"id"`
}

func (q *Queries) RevokeAuthInvite(ctx context.Context, arg RevokeAuthInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAuthInvite, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAuthSessionByID = `-- name: RevokeAuthSessionByID :execrows
UPDATE auth_session
SET revoked_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeAuthSessionByIDParams struct {
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
	ID        string       `db:"id" json:"id"`
}

func (q *Queries) RevokeAuthSessionByID(ctx context.Context, arg RevokeAuthSessionByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAuthSessionByID, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAuthApiKeyLastUsedAt = `-- name: UpdateAuthApiKeyLastUsedAt :execrows
UPDATE auth_api_key
SET last_used_at = ?
WHERE id = ?
`

type UpdateAuthApiKeyLastUsedAtParams struct {
	LastUsedAt sql.NullTime `db:"last_used_at" json:"last_used_at"`
	ID         string       `db:"id" json:"id"`
}

func (q *Queries) UpdateAuthApiKeyLastUsedAt(ctx context.Context, arg UpdateAuthApiKeyLastUsedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAuthApiKeyLastUsedAt, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAuthSessionTokensAndExpiry = `-- name: UpdateAuthSessionTokensAndExpiry :execrows
UPDATE auth_session
SET session_token_hash = ?,
    remember_token_hash = ?,
    expires_at = ?,
    remember_expires_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type UpdateAuthSessionTokensAndExpiryParams struct {
	SessionTokenHash  string    `db:"session_token_hash" json:"session_token_hash"`
	RememberTokenHash string    `db:"remember_token_hash" json:"remember_token_hash"`
	ExpiresAt         time.Time `db:"expires_at" json:"expires_at"`
	RememberExpiresAt time.Time `db:"remember_expires_at" json:"remember_expires_at"`
	ID                string    `db:"id" json:"id"`
}

func (q *Queries) UpdateAuthSessionTokensAndExpiry(ctx context.Context, arg UpdateAuthSessionTokensAndExpiryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAuthSessionTokensAndExpiry,
		arg.SessionTokenHash,
		arg.RememberTokenHash,
		arg.ExpiresAt,
		arg.RememberExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
