// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.sql

package sldb

import (
	"context"
	"strings"
)

const batchArchive = `-- name: BatchArchive :many
UPDATE memo SET row_status = 'archived', updated_at = CURRENT_TIMESTAMP
WHERE memo_uuid IN (/*SLICE:uuids*/?) AND owner_user_id = ?
RETURNING memo_uuid
`

type BatchArchiveParams struct {
	Uuids       []string `db:"uuids" json:"uuids"`
	OwnerUserID int64    `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) BatchArchive(ctx context.Context, arg BatchArchiveParams) ([]string, error) {
	query := batchArchive
	var queryParams []interface{}
	if len(arg.Uuids) > 0 {
		for _, v := range arg.Uuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:uuids*/?", strings.Repeat(",?", len(arg.Uuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:uuids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerUserID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var memo_uuid string
		if err := rows.Scan(&memo_uuid); err != nil {
			return nil, err
		}
		items = append(items, memo_uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchDelete = `-- name: BatchDelete :many
DELETE FROM memo WHERE memo_uuid IN (/*SLICE:uuids*/?) AND owner_user_id = ?
RETURNING memo_uuid
`

type BatchDeleteParams struct {
	Uuids       []string `db:"uuids" json:"uuids"`
	OwnerUserID int64    `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) BatchDelete(ctx context.Context, arg BatchDeleteParams) ([]string, error) {
	query := batchDelete
	var queryParams []interface{}
	if len(arg.Uuids) > 0 {
		for _, v := range arg.Uuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:uuids*/?", strings.Repeat(",?", len(arg.Uuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:uuids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerUserID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var memo_uuid string
		if err := rows.Scan(&memo_uuid); err != nil {
			return nil, err
		}
		items = append(items, memo_uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchPrecheck = `-- name: BatchPrecheck :many
SELECT memo_uuid FROM memo WHERE memo_uuid IN (/*SLICE:uuids*/?) AND owner_user_id = ?
`

type BatchPrecheckParams struct {
	Uuids       []string `db:"uuids" json:"uuids"`
	OwnerUserID int64    `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) BatchPrecheck(ctx context.Context, arg BatchPrecheckParams) ([]string, error) {
	query := batchPrecheck
	var queryParams []interface{}
	if len(arg.Uuids) > 0 {
		for _, v := range arg.Uuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:uuids*/?", strings.Repeat(",?", len(arg.Uuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:uuids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerUserID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var memo_uuid string
		if err := rows.Scan(&memo_uuid); err != nil {
			return nil, err
		}
		items = append(items, memo_uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchSaveTags = `-- name: BatchSaveTags :exec
INSERT OR IGNORE INTO tag (name)
SELECT value FROM json_each(?1)
`

func (q *Queries) BatchSaveTags(ctx context.Context, tags interface{}) error {
	_, err := q.db.ExecContext(ctx, batchSaveTags, tags)
	return err
}

const batchTagAdd = `-- name: BatchTagAdd :exec
INSERT OR IGNORE INTO memo_tag (memo_uuid, tag_name)
SELECT u.value, t.value
FROM json_each(?1) AS u
CROSS JOIN json_each(?2) AS t
`

type BatchTagAddParams struct {
	Uuids interface{} `db:"uuids" json:"uuids"`
	Tags  interface{} `db:"tags" json:"tags"`
}

func (q *Queries) BatchTagAdd(ctx context.Context, arg BatchTagAddParams) error {
	_, err := q.db.ExecContext(ctx, batchTagAdd, arg.Uuids, arg.Tags)
	return err
}

const batchTagRemove = `-- name: BatchTagRemove :exec
DELETE FROM memo_tag
WHERE memo_uuid IN (/*SLICE:uuids*/?) AND tag_name IN (/*SLICE:tags*/?)
`

type BatchTagRemoveParams struct {
	Uuids []string `db:"uuids" json:"uuids"`
	Tags  []string `db:"tags" json:"tags"`
}

func (q *Queries) BatchTagRemove(ctx context.Context, arg BatchTagRemoveParams) error {
	query := batchTagRemove
	var queryParams []interface{}
	if len(arg.Uuids) > 0 {
		for _, v := range arg.Uuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:uuids*/?", strings.Repeat(",?", len(arg.Uuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:uuids*/?", "NULL", 1)
	}
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
