// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memo_history.sql

package sldb

import (
	"context"
	"time"
)

const createMemoHistory = `-- name: CreateMemoHistory :exec
INSERT INTO memo_history (id, memo_uuid, owner_user_id, content, tags, resource_ids)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMemoHistoryParams struct {
	ID          string `db:"id" json:"id"`
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
	Content     string `db:"content" json:"content"`
	Tags        string `db:"tags" json:"tags"`
	ResourceIds string `db:"resource_ids" json:"resource_ids"`
}

func (q *Queries) CreateMemoHistory(ctx context.Context, arg CreateMemoHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createMemoHistory,
		arg.ID,
		arg.MemoUuid,
		arg.OwnerUserID,
		arg.Content,
		arg.Tags,
		arg.ResourceIds,
	)
	return err
}

const deleteOldMemoHistory = `-- name: DeleteOldMemoHistory :execrows
DELETE FROM memo_history
WHERE memo_history.memo_uuid = ? AND memo_history.id NOT IN (
    SELECT h.id FROM memo_history h
    WHERE h.memo_uuid = ?
    ORDER BY h.created_at DESC
    LIMIT ?
)
`

type DeleteOldMemoHistoryParams struct {
	MemoUuid   string `db:"memo_uuid" json:"memo_uuid"`
	MemoUuid_2 string `db:"memo_uuid_2" json:"memo_uuid_2"`
	Limit      int64  `db:"limit" json:"limit"`
}

func (q *Queries) DeleteOldMemoHistory(ctx context.Context, arg DeleteOldMemoHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldMemoHistory, arg.MemoUuid, arg.MemoUuid_2, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemoHistoryByID = `-- name: GetMemoHistoryByID :one
SELECT id, memo_uuid, content, tags, resource_ids, created_at
FROM memo_history
WHERE id = ? AND owner_user_id = ?
`

type GetMemoHistoryByIDParams struct {
	ID          string `db:"id" json:"id"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

type GetMemoHistoryByIDRow struct {
	ID          string    `db:"id" json:"id"`
	MemoUuid    string    `db:"memo_uuid" json:"memo_uuid"`
	Content     string    `db:"content" json:"content"`
	Tags        string    `db:"tags" json:"tags"`
	ResourceIds string    `db:"resource_ids" json:"resource_ids"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) GetMemoHistoryByID(ctx context.Context, arg GetMemoHistoryByIDParams) (GetMemoHistoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMemoHistoryByID, arg.ID, arg.OwnerUserID)
	var i GetMemoHistoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.MemoUuid,
		&i.Content,
		&i.Tags,
		&i.ResourceIds,
		&i.CreatedAt,
	)
	return i, err
}

const listMemoHistory = `-- name: ListMemoHistory :many
SELECT id, memo_uuid, content, tags, resource_ids, created_at
FROM memo_history
WHERE memo_uuid = ? AND owner_user_id = ?
ORDER BY created_at DESC
`

type ListMemoHistoryParams struct {
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

type ListMemoHistoryRow struct {
	ID          string    `db:"id" json:"id"`
	MemoUuid    string    `db:"memo_uuid" json:"memo_uuid"`
	Content     string    `db:"content" json:"content"`
	Tags        string    `db:"tags" json:"tags"`
	ResourceIds string    `db:"resource_ids" json:"resource_ids"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListMemoHistory(ctx context.Context, arg ListMemoHistoryParams) ([]ListMemoHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemoHistory, arg.MemoUuid, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoHistoryRow
	for rows.Next() {
		var i ListMemoHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoUuid,
			&i.Content,
			&i.Tags,
			&i.ResourceIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
