// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memo.sql

package sldb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const appendTagGovernanceAudit = `-- name: AppendTagGovernanceAudit :exec
INSERT INTO tag_governance_audit(action, summary, affected_memos)
VALUES(?, ?, ?)
`

type AppendTagGovernanceAuditParams struct {
	Action        string `db:"action" json:"action"`
	Summary       string `db:"summary" json:"summary"`
	AffectedMemos int64  `db:"affected_memos" json:"affected_memos"`
}

func (q *Queries) AppendTagGovernanceAudit(ctx context.Context, arg AppendTagGovernanceAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendTagGovernanceAudit, arg.Action, arg.Summary, arg.AffectedMemos)
	return err
}

const archiveExpiredMemos = `-- name: ArchiveExpiredMemos :exec
UPDATE memo 
SET row_status = 'archived', updated_at = CURRENT_TIMESTAMP 
WHERE expires_at IS NOT NULL 
AND expires_at < CURRENT_TIMESTAMP 
AND row_status = 'normal'
`

func (q *Queries) ArchiveExpiredMemos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, archiveExpiredMemos)
	return err
}

const archiveExpiredMemosBefore = `-- name: ArchiveExpiredMemosBefore :execrows
UPDATE memo
SET row_status = 'archived', updated_at = ?
WHERE expires_at IS NOT NULL
  AND expires_at < ?
  AND row_status = 'normal'
`

type ArchiveExpiredMemosBeforeParams struct {
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ArchiveExpiredMemosBefore(ctx context.Context, arg ArchiveExpiredMemosBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveExpiredMemosBefore, arg.UpdatedAt, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const archiveMemo = `-- name: ArchiveMemo :exec
UPDATE memo SET row_status = 'archived' WHERE memo_uuid = ? AND owner_user_id = ?
`

type ArchiveMemoParams struct {
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) ArchiveMemo(ctx context.Context, arg ArchiveMemoParams) error {
	_, err := q.db.ExecContext(ctx, archiveMemo, arg.MemoUuid, arg.OwnerUserID)
	return err
}

const cleanupOrphanTags = `-- name: CleanupOrphanTags :exec
DELETE FROM tag 
WHERE name NOT IN (SELECT DISTINCT tag_name FROM memo_tag)
`

func (q *Queries) CleanupOrphanTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOrphanTags)
	return err
}

const countAffectedMemosByTags = `-- name: CountAffectedMemosByTags :one
SELECT COUNT(DISTINCT mt.memo_uuid)
FROM memo_tag mt
JOIN memo m ON mt.memo_uuid = m.memo_uuid
WHERE mt.tag_name IN (/*SLICE:tags*/?)
  AND m.owner_user_id = ?
`

type CountAffectedMemosByTagsParams struct {
	Tags        []string `db:"tags" json:"tags"`
	OwnerUserID int64    `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) CountAffectedMemosByTags(ctx context.Context, arg CountAffectedMemosByTagsParams) (int64, error) {
	query := countAffectedMemosByTags
	var queryParams []interface{}
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OwnerUserID)
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemos = `-- name: CountMemos :one
SELECT COUNT(*) FROM memo WHERE row_status = 'normal' AND owner_user_id = ?
`

func (q *Queries) CountMemos(ctx context.Context, ownerUserID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemos, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resource WHERE owner_user_id = ?
`

func (q *Queries) CountResources(ctx context.Context, ownerUserID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResources, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(DISTINCT tag_name) FROM memo_tag mt
JOIN memo m ON mt.memo_uuid = m.memo_uuid
WHERE m.owner_user_id = ? AND m.row_status = 'normal'
`

func (q *Queries) CountTags(ctx context.Context, ownerUserID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemo = `-- name: CreateMemo :one
INSERT INTO memo (memo_uuid, owner_user_id, content, row_status, expires_at, search_text)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING memo_uuid, content, row_status, expires_at, created_at, updated_at
`

type CreateMemoParams struct {
	MemoUuid    string         `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
	Content     string         `db:"content" json:"content"`
	RowStatus   string         `db:"row_status" json:"row_status"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	SearchText  sql.NullString `db:"search_text" json:"search_text"`
}

type CreateMemoRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMemo(ctx context.Context, arg CreateMemoParams) (CreateMemoRow, error) {
	row := q.db.QueryRowContext(ctx, createMemo,
		arg.MemoUuid,
		arg.OwnerUserID,
		arg.Content,
		arg.RowStatus,
		arg.ExpiresAt,
		arg.SearchText,
	)
	var i CreateMemoRow
	err := row.Scan(
		&i.MemoUuid,
		&i.Content,
		&i.RowStatus,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDuplicateMemoTagLinksByOwner = `-- name: DeleteDuplicateMemoTagLinksByOwner :execrows
DELETE FROM memo_tag
WHERE memo_tag.tag_name = ?
  AND memo_tag.memo_uuid IN (
      SELECT mt2.memo_uuid
      FROM memo_tag mt2
      JOIN memo m2 ON mt2.memo_uuid = m2.memo_uuid
      WHERE mt2.tag_name = ?
        AND m2.owner_user_id = ?
  )
`

type DeleteDuplicateMemoTagLinksByOwnerParams struct {
	TagName     string `db:"tag_name" json:"tag_name"`
	TagName_2   string `db:"tag_name_2" json:"tag_name_2"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) DeleteDuplicateMemoTagLinksByOwner(ctx context.Context, arg DeleteDuplicateMemoTagLinksByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDuplicateMemoTagLinksByOwner, arg.TagName, arg.TagName_2, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemoByUUID = `-- name: DeleteMemoByUUID :execrows
DELETE FROM memo
WHERE memo_uuid = ? AND owner_user_id = ?
`

type DeleteMemoByUUIDParams struct {
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) DeleteMemoByUUID(ctx context.Context, arg DeleteMemoByUUIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemoByUUID, arg.MemoUuid, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMemoTagsByMemoUUID = `-- name: DeleteMemoTagsByMemoUUID :exec
DELETE FROM memo_tag
WHERE memo_uuid = ?
`

func (q *Queries) DeleteMemoTagsByMemoUUID(ctx context.Context, memoUuid string) error {
	_, err := q.db.ExecContext(ctx, deleteMemoTagsByMemoUUID, memoUuid)
	return err
}

const deleteTagAliasByName = `-- name: DeleteTagAliasByName :execrows
DELETE FROM tag_alias
WHERE alias_name = ?
`

func (q *Queries) DeleteTagAliasByName(ctx context.Context, aliasName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagAliasByName, aliasName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagByName = `-- name: DeleteTagByName :execrows
DELETE FROM tag
WHERE name = ?
`

func (q *Queries) DeleteTagByName(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagByName, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCanonicalTagAlias = `-- name: GetCanonicalTagAlias :one
SELECT canonical_name
FROM tag_alias
WHERE alias_name = ?
LIMIT 1
`

func (q *Queries) GetCanonicalTagAlias(ctx context.Context, aliasName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCanonicalTagAlias, aliasName)
	var canonical_name string
	err := row.Scan(&canonical_name)
	return canonical_name, err
}

const getDailyHeatmap = `-- name: GetDailyHeatmap :many
SELECT strftime('%Y-%m-%d', created_at) AS date, COUNT(*) AS count
FROM memo
WHERE row_status = 'normal' AND owner_user_id = ?
GROUP BY date
ORDER BY date ASC
`

type GetDailyHeatmapRow struct {
	Date  interface{} `db:"date" json:"date"`
	Count int64       `db:"count" json:"count"`
}

func (q *Queries) GetDailyHeatmap(ctx context.Context, ownerUserID int64) ([]GetDailyHeatmapRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyHeatmap, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyHeatmapRow
	for rows.Next() {
		var i GetDailyHeatmapRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT strftime('%Y-%m-%d', created_at) as date, COUNT(*) as count
FROM memo
WHERE row_status = 'normal' AND owner_user_id = ?
GROUP BY date
ORDER BY date DESC
LIMIT 365
`

type GetDailyStatsRow struct {
	Date  interface{} `db:"date" json:"date"`
	Count int64       `db:"count" json:"count"`
}

func (q *Queries) GetDailyStats(ctx context.Context, ownerUserID int64) ([]GetDailyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyStats, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyStatsRow
	for rows.Next() {
		var i GetDailyStatsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoByUUID = `-- name: GetMemoByUUID :one
SELECT memo_uuid, content, row_status, expires_at, created_at, updated_at
FROM memo
WHERE memo_uuid = ? AND owner_user_id = ? LIMIT 1
`

type GetMemoByUUIDParams struct {
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

type GetMemoByUUIDRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMemoByUUID(ctx context.Context, arg GetMemoByUUIDParams) (GetMemoByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMemoByUUID, arg.MemoUuid, arg.OwnerUserID)
	var i GetMemoByUUIDRow
	err := row.Scan(
		&i.MemoUuid,
		&i.Content,
		&i.RowStatus,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoTags = `-- name: GetMemoTags :many
SELECT tag_name
FROM memo_tag
WHERE memo_uuid = ?
ORDER BY tag_name ASC
`

func (q *Queries) GetMemoTags(ctx context.Context, memoUuid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMemoTags, memoUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag_name string
		if err := rows.Scan(&tag_name); err != nil {
			return nil, err
		}
		items = append(items, tag_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoTagsBatch = `-- name: GetMemoTagsBatch :many
SELECT memo_uuid, tag_name
FROM memo_tag
WHERE memo_uuid IN (/*SLICE:memo_uuids*/?)
ORDER BY memo_uuid ASC, tag_name ASC
`

func (q *Queries) GetMemoTagsBatch(ctx context.Context, memoUuids []string) ([]MemoTag, error) {
	query := getMemoTagsBatch
	var queryParams []interface{}
	if len(memoUuids) > 0 {
		for _, v := range memoUuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:memo_uuids*/?", strings.Repeat(",?", len(memoUuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:memo_uuids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoTag
	for rows.Next() {
		var i MemoTag
		if err := rows.Scan(&i.MemoUuid, &i.TagName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomMemo = `-- name: GetRandomMemo :one
SELECT memo_uuid, content, row_status, expires_at, created_at, updated_at
FROM memo 
WHERE row_status = 'normal' AND owner_user_id = ?
ORDER BY random() 
LIMIT 1
`

type GetRandomMemoRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetRandomMemo(ctx context.Context, ownerUserID int64) (GetRandomMemoRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomMemo, ownerUserID)
	var i GetRandomMemoRow
	err := row.Scan(
		&i.MemoUuid,
		&i.Content,
		&i.RowStatus,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkMemoTag = `-- name: LinkMemoTag :exec
INSERT INTO memo_tag (memo_uuid, tag_name) VALUES (?, ?)
`

type LinkMemoTagParams struct {
	MemoUuid string `db:"memo_uuid" json:"memo_uuid"`
	TagName  string `db:"tag_name" json:"tag_name"`
}

func (q *Queries) LinkMemoTag(ctx context.Context, arg LinkMemoTagParams) error {
	_, err := q.db.ExecContext(ctx, linkMemoTag, arg.MemoUuid, arg.TagName)
	return err
}

const listAllMemos = `-- name: ListAllMemos :many
SELECT memo_uuid, content, row_status, expires_at, created_at, updated_at
FROM memo 
WHERE row_status = ? AND owner_user_id = ?
ORDER BY created_at DESC 
LIMIT ? OFFSET ?
`

type ListAllMemosParams struct {
	RowStatus   string `db:"row_status" json:"row_status"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

type ListAllMemosRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAllMemos(ctx context.Context, arg ListAllMemosParams) ([]ListAllMemosRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllMemos,
		arg.RowStatus,
		arg.OwnerUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMemosRow
	for rows.Next() {
		var i ListAllMemosRow
		if err := rows.Scan(
			&i.MemoUuid,
			&i.Content,
			&i.RowStatus,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingTagsByNames = `-- name: ListExistingTagsByNames :many
SELECT name
FROM tag
WHERE name IN (/*SLICE:tags*/?)
`

func (q *Queries) ListExistingTagsByNames(ctx context.Context, tags []string) ([]string, error) {
	query := listExistingTagsByNames
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemosByTag = `-- name: ListMemosByTag :many
SELECT m.memo_uuid, m.content, m.row_status, m.expires_at, m.created_at, m.updated_at
FROM memo m
JOIN memo_tag mt ON m.memo_uuid = mt.memo_uuid
WHERE mt.tag_name = ?
AND m.owner_user_id = ?
AND m.row_status = ?
ORDER BY m.created_at DESC
LIMIT ? OFFSET ?
`

type ListMemosByTagParams struct {
	TagName     string `db:"tag_name" json:"tag_name"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
	RowStatus   string `db:"row_status" json:"row_status"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

type ListMemosByTagRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMemosByTag(ctx context.Context, arg ListMemosByTagParams) ([]ListMemosByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemosByTag,
		arg.TagName,
		arg.OwnerUserID,
		arg.RowStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemosByTagRow
	for rows.Next() {
		var i ListMemosByTagRow
		if err := rows.Scan(
			&i.MemoUuid,
			&i.Content,
			&i.RowStatus,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagAliases = `-- name: ListTagAliases :many
SELECT alias_name, canonical_name
FROM tag_alias
ORDER BY alias_name ASC
`

type ListTagAliasesRow struct {
	AliasName     string `db:"alias_name" json:"alias_name"`
	CanonicalName string `db:"canonical_name" json:"canonical_name"`
}

func (q *Queries) ListTagAliases(ctx context.Context) ([]ListTagAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagAliasesRow
	for rows.Next() {
		var i ListTagAliasesRow
		if err := rows.Scan(&i.AliasName, &i.CanonicalName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagAudits = `-- name: ListTagAudits :many
SELECT action, summary, affected_memos, created_at
FROM tag_governance_audit
WHERE (? = '' OR action = ?)
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListTagAuditsParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Action  string      `db:"action" json:"action"`
	Limit   int64       `db:"limit" json:"limit"`
}

type ListTagAuditsRow struct {
	Action        string       `db:"action" json:"action"`
	Summary       string       `db:"summary" json:"summary"`
	AffectedMemos int64        `db:"affected_memos" json:"affected_memos"`
	CreatedAt     sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTagAudits(ctx context.Context, arg ListTagAuditsParams) ([]ListTagAuditsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagAudits, arg.Column1, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagAuditsRow
	for rows.Next() {
		var i ListTagAuditsRow
		if err := rows.Scan(
			&i.Action,
			&i.Summary,
			&i.AffectedMemos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCount = `-- name: ListTagsWithCount :many
SELECT mt.tag_name as name, COUNT(mt.memo_uuid) as count
FROM memo_tag mt
JOIN memo m ON mt.memo_uuid = m.memo_uuid
WHERE m.owner_user_id = ? AND m.row_status = 'normal'
GROUP BY mt.tag_name
ORDER BY count DESC, name ASC
`

type ListTagsWithCountRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) ListTagsWithCount(ctx context.Context, ownerUserID int64) ([]ListTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCount, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithCountRow
	for rows.Next() {
		var i ListTagsWithCountRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveMemoTagLinksByOwner = `-- name: MoveMemoTagLinksByOwner :execrows
UPDATE memo_tag
SET tag_name = ?
WHERE tag_name = ?
  AND memo_uuid IN (
      SELECT memo_uuid
      FROM memo
      WHERE owner_user_id = ?
  )
`

type MoveMemoTagLinksByOwnerParams struct {
	TagName     string `db:"tag_name" json:"tag_name"`
	TagName_2   string `db:"tag_name_2" json:"tag_name_2"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) MoveMemoTagLinksByOwner(ctx context.Context, arg MoveMemoTagLinksByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveMemoTagLinksByOwner, arg.TagName, arg.TagName_2, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveTag = `-- name: SaveTag :exec
INSERT INTO tag (name) VALUES (?) ON CONFLICT (name) DO NOTHING
`

func (q *Queries) SaveTag(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, saveTag, name)
	return err
}

const searchMemos = `-- name: SearchMemos :many
SELECT m.memo_uuid, m.content, m.row_status, m.expires_at, m.created_at, m.updated_at
FROM memo m
JOIN memo_fts f ON m.memo_uuid = f.memo_uuid
WHERE f.content MATCH ?
AND m.owner_user_id = ?
AND m.row_status = ?
ORDER BY f.rank
LIMIT ? OFFSET ?
`

type SearchMemosParams struct {
	Content     string `db:"content" json:"content"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
	RowStatus   string `db:"row_status" json:"row_status"`
	Limit       int64  `db:"limit" json:"limit"`
	Offset      int64  `db:"offset" json:"offset"`
}

type SearchMemosRow struct {
	MemoUuid  string       `db:"memo_uuid" json:"memo_uuid"`
	Content   string       `db:"content" json:"content"`
	RowStatus string       `db:"row_status" json:"row_status"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchMemos(ctx context.Context, arg SearchMemosParams) ([]SearchMemosRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemos,
		arg.Content,
		arg.OwnerUserID,
		arg.RowStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemosRow
	for rows.Next() {
		var i SearchMemosRow
		if err := rows.Scan(
			&i.MemoUuid,
			&i.Content,
			&i.RowStatus,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagExists = `-- name: TagExists :one
SELECT COUNT(1)
FROM tag
WHERE name = ?
`

func (q *Queries) TagExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, tagExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMemoContent = `-- name: UpdateMemoContent :exec
UPDATE memo 
SET content = ?
WHERE memo_uuid = ? AND owner_user_id = ?
`

type UpdateMemoContentParams struct {
	Content     string `db:"content" json:"content"`
	MemoUuid    string `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) UpdateMemoContent(ctx context.Context, arg UpdateMemoContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMemoContent, arg.Content, arg.MemoUuid, arg.OwnerUserID)
	return err
}

const updateMemoContentAndExpires = `-- name: UpdateMemoContentAndExpires :execrows
UPDATE memo
SET content = ?,
    expires_at = ?,
    search_text = ?
WHERE memo_uuid = ? AND owner_user_id = ?
`

type UpdateMemoContentAndExpiresParams struct {
	Content     string         `db:"content" json:"content"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	SearchText  sql.NullString `db:"search_text" json:"search_text"`
	MemoUuid    string         `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) UpdateMemoContentAndExpires(ctx context.Context, arg UpdateMemoContentAndExpiresParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMemoContentAndExpires,
		arg.Content,
		arg.ExpiresAt,
		arg.SearchText,
		arg.MemoUuid,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMemoRowStatus = `-- name: UpdateMemoRowStatus :execrows
UPDATE memo
SET row_status = ?
WHERE memo_uuid = ?
`

type UpdateMemoRowStatusParams struct {
	RowStatus string `db:"row_status" json:"row_status"`
	MemoUuid  string `db:"memo_uuid" json:"memo_uuid"`
}

func (q *Queries) UpdateMemoRowStatus(ctx context.Context, arg UpdateMemoRowStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMemoRowStatus, arg.RowStatus, arg.MemoUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertTagAlias = `-- name: UpsertTagAlias :exec
INSERT INTO tag_alias(alias_name, canonical_name)
VALUES(?, ?)
ON CONFLICT(alias_name) DO UPDATE
SET canonical_name = excluded.canonical_name
`

type UpsertTagAliasParams struct {
	AliasName     string `db:"alias_name" json:"alias_name"`
	CanonicalName string `db:"canonical_name" json:"canonical_name"`
}

func (q *Queries) UpsertTagAlias(ctx context.Context, arg UpsertTagAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertTagAlias, arg.AliasName, arg.CanonicalName)
	return err
}
