// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sldb

import (
	"database/sql"
	"time"
)

type AuthApiKey struct {
	ID         string       `db:"id" json:"id"`
	UserID     int64        `db:"user_id" json:"user_id"`
	KeyHash    string       `db:"key_hash" json:"key_hash"`
	Label      string       `db:"label" json:"label"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	ExpiresAt  sql.NullTime `db:"expires_at" json:"expires_at"`
	LastUsedAt sql.NullTime `db:"last_used_at" json:"last_used_at"`
}

type AuthInvite struct {
	ID        string        `db:"id" json:"id"`
	CodeHash  string        `db:"code_hash" json:"code_hash"`
	Role      string        `db:"role" json:"role"`
	ExpiresAt time.Time     `db:"expires_at" json:"expires_at"`
	UsedAt    sql.NullTime  `db:"used_at" json:"used_at"`
	UsedBy    sql.NullInt64 `db:"used_by" json:"used_by"`
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	RevokedAt sql.NullTime  `db:"revoked_at" json:"revoked_at"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
}

type AuthSession struct {
	ID                string       `db:"id" json:"id"`
	UserID            int64        `db:"user_id" json:"user_id"`
	SessionTokenHash  string       `db:"session_token_hash" json:"session_token_hash"`
	RememberTokenHash string       `db:"remember_token_hash" json:"remember_token_hash"`
	ExpiresAt         time.Time    `db:"expires_at" json:"expires_at"`
	RememberExpiresAt time.Time    `db:"remember_expires_at" json:"remember_expires_at"`
	RevokedAt         sql.NullTime `db:"revoked_at" json:"revoked_at"`
	UserAgent         string       `db:"user_agent" json:"user_agent"`
	ClientIp          string       `db:"client_ip" json:"client_ip"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at" json:"updated_at"`
}

type AuthUser struct {
	ID           int64     `db:"id" json:"id"`
	Username     string    `db:"username" json:"username"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	Role         string    `db:"role" json:"role"`
	Status       string    `db:"status" json:"status"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

type Memo struct {
	MemoUuid    string         `db:"memo_uuid" json:"memo_uuid"`
	Content     string         `db:"content" json:"content"`
	RowStatus   string         `db:"row_status" json:"row_status"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	SearchText  sql.NullString `db:"search_text" json:"search_text"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type MemoFt struct {
	MemoUuid string `db:"memo_uuid" json:"memo_uuid"`
	Content  string `db:"content" json:"content"`
}

type MemoHistory struct {
	ID          string    `db:"id" json:"id"`
	MemoUuid    string    `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64     `db:"owner_user_id" json:"owner_user_id"`
	Content     string    `db:"content" json:"content"`
	Tags        string    `db:"tags" json:"tags"`
	ResourceIds string    `db:"resource_ids" json:"resource_ids"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type MemoTag struct {
	MemoUuid string `db:"memo_uuid" json:"memo_uuid"`
	TagName  string `db:"tag_name" json:"tag_name"`
}

type Resource struct {
	ID           string         `db:"id" json:"id"`
	MemoUuid     sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID  int64          `db:"owner_user_id" json:"owner_user_id"`
	Filename     string         `db:"filename" json:"filename"`
	Hash         string         `db:"hash" json:"hash"`
	Size         int64          `db:"size" json:"size"`
	MimeType     string         `db:"mime_type" json:"mime_type"`
	InternalPath string         `db:"internal_path" json:"internal_path"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

type Tag struct {
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type TagAlias struct {
	AliasName     string       `db:"alias_name" json:"alias_name"`
	CanonicalName string       `db:"canonical_name" json:"canonical_name"`
	CreatedAt     sql.NullTime `db:"created_at" json:"created_at"`
}

type TagGovernanceAudit struct {
	ID            int64        `db:"id" json:"id"`
	Action        string       `db:"action" json:"action"`
	Summary       string       `db:"summary" json:"summary"`
	AffectedMemos int64        `db:"affected_memos" json:"affected_memos"`
	CreatedAt     sql.NullTime `db:"created_at" json:"created_at"`
}

type TagSet struct {
	ID          string         `db:"id" json:"id"`
	UserID      int64          `db:"user_id" json:"user_id"`
	GroupID     sql.NullString `db:"group_id" json:"group_id"`
	Name        string         `db:"name" json:"name"`
	TagsAny     string         `db:"tags_any" json:"tags_any"`
	TagsAll     string         `db:"tags_all" json:"tags_all"`
	TagsExclude string         `db:"tags_exclude" json:"tags_exclude"`
	Weight      int64          `db:"weight" json:"weight"`
	LastUsedAt  sql.NullTime   `db:"last_used_at" json:"last_used_at"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type TagSetGroup struct {
	ID        string    `db:"id" json:"id"`
	UserID    int64     `db:"user_id" json:"user_id"`
	Name      string    `db:"name" json:"name"`
	Weight    int64     `db:"weight" json:"weight"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
