// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sldb

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AppendTagGovernanceAudit(ctx context.Context, arg AppendTagGovernanceAuditParams) error
	ArchiveExpiredMemos(ctx context.Context) error
	ArchiveExpiredMemosBefore(ctx context.Context, arg ArchiveExpiredMemosBeforeParams) (int64, error)
	ArchiveMemo(ctx context.Context, arg ArchiveMemoParams) error
	BatchArchive(ctx context.Context, arg BatchArchiveParams) ([]string, error)
	BatchDelete(ctx context.Context, arg BatchDeleteParams) ([]string, error)
	BatchPrecheck(ctx context.Context, arg BatchPrecheckParams) ([]string, error)
	BatchSaveTags(ctx context.Context, tags interface{}) error
	BatchTagAdd(ctx context.Context, arg BatchTagAddParams) error
	BatchTagRemove(ctx context.Context, arg BatchTagRemoveParams) error
	CleanupOrphanResources(ctx context.Context) (int64, error)
	CleanupOrphanTags(ctx context.Context) error
	CountActiveAuthInvitesByCreatorAndRole(ctx context.Context, arg CountActiveAuthInvitesByCreatorAndRoleParams) (int64, error)
	CountAffectedMemosByTags(ctx context.Context, arg CountAffectedMemosByTagsParams) (int64, error)
	CountAuthUsers(ctx context.Context) (int64, error)
	CountMemos(ctx context.Context, ownerUserID int64) (int64, error)
	CountResources(ctx context.Context, ownerUserID int64) (int64, error)
	CountTags(ctx context.Context, ownerUserID int64) (int64, error)
	CreateAuthApiKey(ctx context.Context, arg CreateAuthApiKeyParams) error
	CreateAuthInvite(ctx context.Context, arg CreateAuthInviteParams) error
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (CreateAuthUserRow, error)
	CreateMemo(ctx context.Context, arg CreateMemoParams) (CreateMemoRow, error)
	CreateMemoHistory(ctx context.Context, arg CreateMemoHistoryParams) error
	CreateResource(ctx context.Context, arg CreateResourceParams) error
	DeleteAuthApiKey(ctx context.Context, arg DeleteAuthApiKeyParams) (int64, error)
	DeleteAuthUserByID(ctx context.Context, id int64) (int64, error)
	DeleteDuplicateMemoTagLinksByOwner(ctx context.Context, arg DeleteDuplicateMemoTagLinksByOwnerParams) (int64, error)
	DeleteExpiredAuthSessions(ctx context.Context, rememberExpiresAt time.Time) (int64, error)
	DeleteMemoByUUID(ctx context.Context, arg DeleteMemoByUUIDParams) (int64, error)
	DeleteMemoTagsByMemoUUID(ctx context.Context, memoUuid string) error
	DeleteOldMemoHistory(ctx context.Context, arg DeleteOldMemoHistoryParams) (int64, error)
	DeleteTagAliasByName(ctx context.Context, aliasName string) (int64, error)
	DeleteTagByName(ctx context.Context, name string) (int64, error)
	GetAuthApiKeyByKeyHash(ctx context.Context, keyHash string) (AuthApiKey, error)
	GetAuthInviteByCodeHash(ctx context.Context, codeHash string) (AuthInvite, error)
	GetAuthSessionByRememberTokenHash(ctx context.Context, rememberTokenHash string) (AuthSession, error)
	GetAuthSessionBySessionTokenHash(ctx context.Context, sessionTokenHash string) (AuthSession, error)
	GetAuthUserByID(ctx context.Context, id int64) (AuthUser, error)
	GetAuthUserByUsername(ctx context.Context, username string) (AuthUser, error)
	GetCanonicalTagAlias(ctx context.Context, aliasName string) (string, error)
	GetDailyHeatmap(ctx context.Context, ownerUserID int64) ([]GetDailyHeatmapRow, error)
	GetDailyStats(ctx context.Context, ownerUserID int64) ([]GetDailyStatsRow, error)
	GetMemoByUUID(ctx context.Context, arg GetMemoByUUIDParams) (GetMemoByUUIDRow, error)
	GetMemoHistoryByID(ctx context.Context, arg GetMemoHistoryByIDParams) (GetMemoHistoryByIDRow, error)
	GetMemoTags(ctx context.Context, memoUuid string) ([]string, error)
	GetMemoTagsBatch(ctx context.Context, memoUuids []string) ([]MemoTag, error)
	GetRandomMemo(ctx context.Context, ownerUserID int64) (GetRandomMemoRow, error)
	GetResourceByID(ctx context.Context, arg GetResourceByIDParams) (Resource, error)
	LinkMemoTag(ctx context.Context, arg LinkMemoTagParams) error
	LinkResourceToMemo(ctx context.Context, arg LinkResourceToMemoParams) error
	ListActiveAuthInvitesByCreator(ctx context.Context, arg ListActiveAuthInvitesByCreatorParams) ([]AuthInvite, error)
	ListAllMemos(ctx context.Context, arg ListAllMemosParams) ([]ListAllMemosRow, error)
	ListAllResources(ctx context.Context, ownerUserID int64) ([]Resource, error)
	ListAuthApiKeysByUserID(ctx context.Context, userID int64) ([]AuthApiKey, error)
	ListAuthInvitesByCreator(ctx context.Context, arg ListAuthInvitesByCreatorParams) ([]AuthInvite, error)
	ListExistingTagsByNames(ctx context.Context, tags []string) ([]string, error)
	ListExpiredAuthInvitesByCreator(ctx context.Context, arg ListExpiredAuthInvitesByCreatorParams) ([]AuthInvite, error)
	ListMemoHistory(ctx context.Context, arg ListMemoHistoryParams) ([]ListMemoHistoryRow, error)
	ListMemoResourcesBatch(ctx context.Context, memoUuids []sql.NullString) ([]ListMemoResourcesBatchRow, error)
	ListMemosByTag(ctx context.Context, arg ListMemosByTagParams) ([]ListMemosByTagRow, error)
	ListResourcesByMemoUUID(ctx context.Context, arg ListResourcesByMemoUUIDParams) ([]Resource, error)
	ListRevokedAuthInvitesByCreator(ctx context.Context, arg ListRevokedAuthInvitesByCreatorParams) ([]AuthInvite, error)
	ListTagAliases(ctx context.Context) ([]ListTagAliasesRow, error)
	ListTagAudits(ctx context.Context, arg ListTagAuditsParams) ([]ListTagAuditsRow, error)
	ListTagsWithCount(ctx context.Context, ownerUserID int64) ([]ListTagsWithCountRow, error)
	ListTrackedPaths(ctx context.Context) ([]string, error)
	ListUsedAuthInvitesByCreator(ctx context.Context, arg ListUsedAuthInvitesByCreatorParams) ([]AuthInvite, error)
	MarkAuthInviteUsed(ctx context.Context, arg MarkAuthInviteUsedParams) (int64, error)
	MoveMemoTagLinksByOwner(ctx context.Context, arg MoveMemoTagLinksByOwnerParams) (int64, error)
	ResourceExistsForOwner(ctx context.Context, arg ResourceExistsForOwnerParams) (int64, error)
	RevokeAuthInvite(ctx context.Context, arg RevokeAuthInviteParams) (int64, error)
	RevokeAuthSessionByID(ctx context.Context, arg RevokeAuthSessionByIDParams) (int64, error)
	SaveTag(ctx context.Context, name string) error
	SearchMemos(ctx context.Context, arg SearchMemosParams) ([]SearchMemosRow, error)
	TagExists(ctx context.Context, name string) (int64, error)
	UnlinkMemoResourcesByOwner(ctx context.Context, arg UnlinkMemoResourcesByOwnerParams) (int64, error)
	UpdateAuthApiKeyLastUsedAt(ctx context.Context, arg UpdateAuthApiKeyLastUsedAtParams) (int64, error)
	UpdateAuthSessionTokensAndExpiry(ctx context.Context, arg UpdateAuthSessionTokensAndExpiryParams) (int64, error)
	UpdateMemoContent(ctx context.Context, arg UpdateMemoContentParams) error
	UpdateMemoContentAndExpires(ctx context.Context, arg UpdateMemoContentAndExpiresParams) (int64, error)
	UpdateMemoRowStatus(ctx context.Context, arg UpdateMemoRowStatusParams) (int64, error)
	UpsertTagAlias(ctx context.Context, arg UpsertTagAliasParams) error
}

var _ Querier = (*Queries)(nil)
