// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package sldb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const cleanupOrphanResources = `-- name: CleanupOrphanResources :execrows
DELETE FROM resource
WHERE memo_uuid IS NULL 
  AND id NOT IN (
      SELECT DISTINCT json_each.value
      FROM memo_history, json_each(memo_history.resource_ids)
  )
`

func (q *Queries) CleanupOrphanResources(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupOrphanResources)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createResource = `-- name: CreateResource :exec
INSERT INTO resource (id, memo_uuid, owner_user_id, filename, hash, size, mime_type, internal_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateResourceParams struct {
	ID           string         `db:"id" json:"id"`
	MemoUuid     sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID  int64          `db:"owner_user_id" json:"owner_user_id"`
	Filename     string         `db:"filename" json:"filename"`
	Hash         string         `db:"hash" json:"hash"`
	Size         int64          `db:"size" json:"size"`
	MimeType     string         `db:"mime_type" json:"mime_type"`
	InternalPath string         `db:"internal_path" json:"internal_path"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.MemoUuid,
		arg.OwnerUserID,
		arg.Filename,
		arg.Hash,
		arg.Size,
		arg.MimeType,
		arg.InternalPath,
	)
	return err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, memo_uuid, owner_user_id, filename, hash, size, mime_type, internal_path, created_at
FROM resource WHERE id = ? AND owner_user_id = ? LIMIT 1
`

type GetResourceByIDParams struct {
	ID          string `db:"id" json:"id"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) GetResourceByID(ctx context.Context, arg GetResourceByIDParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByID, arg.ID, arg.OwnerUserID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.MemoUuid,
		&i.OwnerUserID,
		&i.Filename,
		&i.Hash,
		&i.Size,
		&i.MimeType,
		&i.InternalPath,
		&i.CreatedAt,
	)
	return i, err
}

const linkResourceToMemo = `-- name: LinkResourceToMemo :exec
UPDATE resource SET memo_uuid = ? WHERE id = ? AND owner_user_id = ?
`

type LinkResourceToMemoParams struct {
	MemoUuid    sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	ID          string         `db:"id" json:"id"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) LinkResourceToMemo(ctx context.Context, arg LinkResourceToMemoParams) error {
	_, err := q.db.ExecContext(ctx, linkResourceToMemo, arg.MemoUuid, arg.ID, arg.OwnerUserID)
	return err
}

const listAllResources = `-- name: ListAllResources :many
SELECT id, memo_uuid, owner_user_id, filename, hash, size, mime_type, internal_path, created_at
FROM resource WHERE owner_user_id = ?
`

func (q *Queries) ListAllResources(ctx context.Context, ownerUserID int64) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listAllResources, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.MemoUuid,
			&i.OwnerUserID,
			&i.Filename,
			&i.Hash,
			&i.Size,
			&i.MimeType,
			&i.InternalPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoResourcesBatch = `-- name: ListMemoResourcesBatch :many
SELECT id, memo_uuid, filename, hash, size, mime_type, internal_path, created_at
FROM resource
WHERE memo_uuid IN (/*SLICE:memo_uuids*/?)
ORDER BY memo_uuid ASC, created_at ASC
`

type ListMemoResourcesBatchRow struct {
	ID           string         `db:"id" json:"id"`
	MemoUuid     sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	Filename     string         `db:"filename" json:"filename"`
	Hash         string         `db:"hash" json:"hash"`
	Size         int64          `db:"size" json:"size"`
	MimeType     string         `db:"mime_type" json:"mime_type"`
	InternalPath string         `db:"internal_path" json:"internal_path"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) ListMemoResourcesBatch(ctx context.Context, memoUuids []sql.NullString) ([]ListMemoResourcesBatchRow, error) {
	query := listMemoResourcesBatch
	var queryParams []interface{}
	if len(memoUuids) > 0 {
		for _, v := range memoUuids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:memo_uuids*/?", strings.Repeat(",?", len(memoUuids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:memo_uuids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoResourcesBatchRow
	for rows.Next() {
		var i ListMemoResourcesBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoUuid,
			&i.Filename,
			&i.Hash,
			&i.Size,
			&i.MimeType,
			&i.InternalPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByMemoUUID = `-- name: ListResourcesByMemoUUID :many
SELECT id, memo_uuid, owner_user_id, filename, hash, size, mime_type, internal_path, created_at
FROM resource WHERE memo_uuid = ? AND owner_user_id = ?
`

type ListResourcesByMemoUUIDParams struct {
	MemoUuid    sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) ListResourcesByMemoUUID(ctx context.Context, arg ListResourcesByMemoUUIDParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByMemoUUID, arg.MemoUuid, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.MemoUuid,
			&i.OwnerUserID,
			&i.Filename,
			&i.Hash,
			&i.Size,
			&i.MimeType,
			&i.InternalPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedPaths = `-- name: ListTrackedPaths :many
SELECT internal_path
FROM resource
`

func (q *Queries) ListTrackedPaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var internal_path string
		if err := rows.Scan(&internal_path); err != nil {
			return nil, err
		}
		items = append(items, internal_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourceExistsForOwner = `-- name: ResourceExistsForOwner :one
SELECT COUNT(1)
FROM resource
WHERE id = ? AND owner_user_id = ?
`

type ResourceExistsForOwnerParams struct {
	ID          string `db:"id" json:"id"`
	OwnerUserID int64  `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) ResourceExistsForOwner(ctx context.Context, arg ResourceExistsForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, resourceExistsForOwner, arg.ID, arg.OwnerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unlinkMemoResourcesByOwner = `-- name: UnlinkMemoResourcesByOwner :execrows
UPDATE resource
SET memo_uuid = NULL
WHERE memo_uuid = ? AND owner_user_id = ?
`

type UnlinkMemoResourcesByOwnerParams struct {
	MemoUuid    sql.NullString `db:"memo_uuid" json:"memo_uuid"`
	OwnerUserID int64          `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) UnlinkMemoResourcesByOwner(ctx context.Context, arg UnlinkMemoResourcesByOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlinkMemoResourcesByOwner, arg.MemoUuid, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
